apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  annotations:
    anywhere.eks.amazonaws.com/managed-by-cli: "true"
    anywhere.eks.amazonaws.com/management-components-version: v0.27.0-dev+build.17
  name: main-i-09797-f72f3de
  namespace: default
spec:
  clusterNetwork:
    cniConfig:
      cilium: {}
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 1
    machineHealthCheck:
      maxUnhealthy: 100%
  datacenterRef:
    kind: DockerDatacenterConfig
    name: main-i-09797-f72f3de
  eksaVersion: v0.27.0-dev+build.17
  externalEtcdConfiguration:
    count: 1
  gitOpsRef:
    kind: FluxConfig
    name: eksa-test
  kubernetesVersion: "1.36"
  licenseToken: eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJsaWNlbnNlSWQiOiJsLTAxMTNhZjZiOWY4OTRlZGU5NzhkYWEzYmRlZGUwYjc4IiwibGljZW5zZVZlcnNpb24iOiIxIiwiYmVnaW5WYWxpZGl0eSI6IjIwMjUtMDItMjVUMDA6MzA6NDMuMDAwWiIsImVuZFZhbGlkaXR5IjoiMjAyOC0wMi0yNlQwMDozMDo0My4wMDBaIiwic3Vic2NyaXB0aW9uSWQiOiJiMWM0NmNmMS04YzVlLTQzN2QtYTJjYy00MTdiMDZmOWI0Y3I6ZmU4M2MzOTciLCJzdWJzY3JpcHRpb25OYW1lIjoiYm90dGxlcm9ja2V0LWVrc2EtdGVzdHMiLCJhY2NvdW50SWQiOiI2NTkzNTYzOTg0MDQiLCJyZWdpb24iOiJ1cy13ZXN0LTIifQ.7QZj679HcQHYwQnQuZRZDaugigc-gQnxMbIL_1fftq6xwxZ2WtOU3xha8_zK6TE4n2wbCXgnbdNljrSbdCKI5w
  machineHealthCheck:
    maxUnhealthy: 100%
    nodeStartupTimeout: 10m0s
    unhealthyMachineTimeout: 5m0s
  managementCluster:
    name: main-i-09797-f72f3de
  packages:
    disable: true
  workerNodeGroupConfigurations:
  - count: 3
    machineHealthCheck:
      maxUnhealthy: 40%
    name: md-0

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: DockerDatacenterConfig
metadata:
  name: main-i-09797-f72f3de
  namespace: default
spec: {}

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: FluxConfig
metadata:
  name: eksa-test
  namespace: default
spec:
  branch: quick-e2e-test-fe0a5999-e741-4871-b00d-fdff4a84a377-1
  clusterConfigPath: quick-e2e-test-fe0a5999-e741-4871-b00d-fdff4a84a377-1
  git:
    repositoryUrl: ssh://git@github.com/that-jetpack-guy/quick-e2e-test-fe0a5999-e741-4871-b00d-fdff4a84a377-1.git
  systemNamespace: default

---
